//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aanchalibookshop_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aanchalbookshop_Entities1 : DbContext
    {
        public aanchalbookshop_Entities1()
            : base("name=aanchalbookshop_Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<orderdetail> orderdetails { get; set; }
        public virtual DbSet<productdetail> productdetails { get; set; }
        public virtual DbSet<productimage> productimages { get; set; }
        public virtual DbSet<userdetail> userdetails { get; set; }
    }
}
