//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aanchalibookshop_
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int detail_id { get; set; }
        public Nullable<int> or_id { get; set; }
        public int p_id { get; set; }
        public int p_qty { get; set; }
        public decimal p_price { get; set; }
        public Nullable<decimal> p_total { get; set; }
    
        public virtual order order { get; set; }
        public virtual productdetail productdetail { get; set; }
    }
}
