//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aanchalibookshop_
{
    using System;
    using System.Collections.Generic;
    
    public partial class productimage
    {
        public int image_id { get; set; }
        public Nullable<int> p_id { get; set; }
    
        public virtual productdetail productdetail { get; set; }
    }
}
